In [132]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import scipy.optimize as opt
from scipy.io import loadmat
import econtools 
import econtools.metrics as mt
import statsmodels.discrete.discrete_model as sm
import matplotlib.pyplot as plt
import itertools as it
import copy

# mine
import demand_discrete_choice.DiscreteChoice as dc
import importlib
importlib.reload(dc)

In [133]:
# ------------------------------------------------------------------------
# NOTE
# ------------------------------------------------------------------------
# Purpose: HW2 
# 
# Import data and stats
# 
#
# ------------------------------------------------------------------------

# Initialize file path

In [134]:
rootpath = '/Users/jingyuanwang/Dropbox/Course/ECON/IO/NU450/NU450_HW/450-1-HW2'
datapath = rootpath + '/' + 'data'
resultpath = rootpath + '/' + 'results'

# Parameters
Everything should be input in the following cell. 
All other cells are just operation and calculation.

In [135]:
# model parameters (true value)
true_parameters = {'beta': np.array([5,1,1]),
                   'alpha_0': 1,
                   'alpha_sigma':1,
                   'gamma': np.array([2,1,1])}

# import file names
matfiles = ['10markets3products', '100markets3products','100markets5products']
names = ['m10_prod3', 'm100_prod3', 'm100_prod5']

# Import Data

In [136]:
# 1 import
inputfiles = dict(zip(names, matfiles))
data = {}
for name, filename in inputfiles.items():
    file = datapath + '/Simulation Data/'+ filename
    data[name] = loadmat(file)

In [150]:
# 2. clean
sample = 'm100_prod3'
num_of_market = 100
num_of_prod = 3
df_product = (pd.DataFrame(np.concatenate( 
                          (data[sample]['x1'],
                           data[sample]['xi_all'],
                           data[sample]['w'], 
                           data[sample]['Z'],
                           data[sample]['eta']), axis = 1 ))
              .rename(columns = {0:'x1',1:'x2',2:'x3',3:'xi', 4:'w', 5:'z',6:'eta'}) )
df_product['price'] = np.reshape(data[sample]['P_opt'], (num_of_market*num_of_prod,1))

df_product['market_id'] = np.repeat(np.arange(num_of_market)[:,np.newaxis], num_of_prod, axis = 0)

df_product['product_id'] = (np.repeat(np.arange(num_of_prod)[:, np.newaxis], 
                                      num_of_market, axis=1)
                                .reshape((num_of_prod*num_of_market,1), order = 'F') )
product_ids = {'market_id':'market_id',
               'product_id':'product_id'}

# consumer
df_consumer = pd.DataFrame(data[sample]['alphas'].T, columns=[idx for idx in range(num_of_market) ])
df_consumer = df_consumer.stack().reset_index().rename(columns = {'level_0':'consumer_id', 
                                                                  'level_1':'market_id',
                                                                  0:'alpha'})


consumer_ids = {'market_id':'market_id',
               'consumer_id':'consumer_id'}

In [151]:
# 3. fit it into a class: discrete choice

demand_m10_prod3 = dc.DiscreteChoice(df_consumer, consumer_ids, df_product, product_ids, true_parameters=true_parameters)

# Simulate consumer choice and welfare

In [152]:
# Outline
# 1. simulate choice
# 2. compare with the given market share variable
# 3. save observables and final choice as a sample dataset. Make this a class
# 4. calculate welfare

In [153]:
product_attribute_observed = ['x1','x2','x3']
product_attribute_unobs = 'xi'
price = 'price'
taste = demand_m10_prod3.true_par['beta']
price_sensitivity = 'alpha'

demand_m10_prod3.simulate_consumer_choice(product_attribute_observed, product_attribute_unobs, price,
                                    taste, price_sensitivity)

In [147]:
demand_m10_prod3

      consumer_id  market_id      alpha    utility  choice
0               0          0   2.139052  20.428421       2
10              1          0   2.349077  21.617263       2
20              2          0   4.238199  32.310574       2
30              3          0   1.806646  18.546847       2
40              4          0   1.781032  18.401865       2
50              5          0   2.483962  22.380775       2
60              6          0   1.272563  15.523693       2
70              7          0   8.137757  54.383888       2
80              8          0   1.677599  17.816381       2
90              9          0   4.464417  33.591073       2
100            10          0   2.901204  24.742559       2
110            11          0   1.379615  16.129653       2
120            12          0   1.983222  19.546349       2
130            13          0   1.442714  16.486825       2
140            14          0   9.806727  63.831035       2
150            15          0   1.176855  14.981941       2
160            16          0   1.685221  17.859525       2
170            17          0   1.524404  16.949227       2
180            18          0   4.452633  33.524372       2
190            19          0   1.564840  17.178115       2
200            20          0   2.165077  20.575736       2
210            21          0   2.492582  22.429567       2
220            22          0   1.938348  19.292345       2
230            23          0  12.822793  80.903377       2
240            24          0   3.123376  26.000155       2
250            25          0   2.186604  20.697590       2
260            26          0   2.958570  25.067275       2
270            27          0   1.203445  15.132448       2
280            28          0   1.464581  16.610605       2
290            29          0   2.307341  21.381016       2
...           ...        ...        ...        ...     ...
4709          470          9   1.883860  12.638284       1
4719          471          9   1.632686  11.647108       1
4729          472          9   2.451286  14.877444       1
4739          473          9   1.502696  11.134147       1
4749          474          9   1.412329  10.905707       0
4759          475          9   3.742959  19.974608       1
4769          476          9   4.562438  23.208412       1
4779          477          9   3.215183  17.891913       1
4789          478          9   1.588156  11.471388       1
4799          479          9   6.673036  31.537194       1
4809          480          9   1.372915  10.826096       0
4819          481          9   1.609867  11.557063       1
4829          482          9   2.856955  16.478283       1
4839          483          9   2.706874  15.886037       1
4849          484          9   3.369838  18.502210       1
4859          485          9   1.271270  10.620786       0
4869          486          9   1.902901  12.713424       1
4879          487          9   2.578522  15.379541       1
4889          488          9   3.809106  20.235634       1
4899          489          9   2.007883  13.127700       1
4909          490          9   1.720425  11.993341       1
4919          491          9  11.742148  51.540774       1
4929          492          9   3.997553  20.979280       1
4939          493          9   1.521234  11.207301       1
4949          494          9   2.014157  13.152458       1
4959          495          9   2.415158  14.734876       1
4969          496          9   1.227808  10.532997       0
4979          497          9   1.779572  12.226748       1
4989          498          9   2.219488  13.962730       1
4999          499          9   1.723941  12.007219       1

[5000 rows x 5 columns]

In [ ]:
def consumer_welfare( , choice):
    # scalar operation
    
    return 1

In [ ]:
def hist():
    
    
    
    return 1

# Estimation

In [179]:
num_of_market = max(len(df_product[consumer_ids['market_id']].unique()),  
                            len(df_product[product_ids['market_id']].unique()) )

In [185]:
max_num_of_consumer_withinmarket = df_consumer[consumer_ids].groupby(consumer_ids['market_id']).count().max()
max_num_of_prod_withinmarket = df_product[product_ids].groupby(product_ids['market_id']).count().max()

In [187]:
max_num_of_prod_withinmarket

product_id    3
dtype: int64

In [170]:
df_panel = pd.merge(panel_index, df_product, 
                 how= 'right',
                 left_on = [ panel_ids[key] for key in ('market_id','product_id')],
                 right_on =  list(product_ids.values()) )

In [174]:
df_panel.iloc[0:500,]

In [175]:
df_panel.sort_index(inplace = True)

In [ ]:
demand_m10_prod3.consumer_product.apply( lambda x: x+y, axis)

In [ ]:
df['']= demand_m10_prod3.consumer_product.head().apply(lambda row : row.x1 + row.x2, axis=1)

In [ ]:
# Outline
# 1. simulate choice
# 2. compare with the given market share variable
# 3. save observables and final choice as a sample dataset. Make this a class
# 4. calculate welfare

In [ ]:
#1. answer questions

In [ ]:
#2. estimate delta and xi, compare with real data